### ISSUE TITLE
[Feature]: Add pagination to Table component

### ISSUE THREAD

**Issue by qurashiakeel** [tremorlabs/tremor-npm#512] opened 2023-06-10 02:55 UTC
### What problem does this feature solve?

The pagination feature is really important for the table component, most of the times we have hundreds of items which can't be shown in single page and it if we need to handle it manually that messes up the code. It would be awesome to have the built in pagination feature.

**Comment by severinlandolt** [comment] 2023-06-10 05:01
This is a duplicate of #283

**Closed as completed by severinlandolt** 2023-06-10 05:01 UTC
Labels: Hint: Duplicate

**Comment by Iqueal** [comment] 2023-06-10 09:00
So where is the pagination?
