### ISSUE TITLE
date range picker keeps last two selected options gray

### ISSUE THREAD

**Issue by TheBuilderJR** [tremorlabs/tremor-npm#312] opened 2023-02-27 11:59 UTC
<img width="472" alt="Screen Shot 2023-02-27 at 8 00 11 PM" src="https://user-images.githubusercontent.com/46176773/221558438-d33a47c3-1fb5-47fc-b41d-4601f6fc5079.png">

my code looks like this

```
    <div className="min-w-[165px]">
      <DateRangePicker
        value={dateRangePickerValue}
        onValueChange={onDateRangePickerValueChange}
        options={dateFilterOptions}
        enableYearPagination
      />
    </div>
```

**Comment by mitrotasios** [comment] 2023-03-03 14:13
Hey @TheBuilderJR, thanks for reporting this, we'll look into it!

**Comment by TheBuilderJR** [comment] 2023-03-03 14:27
Sweet! FWIW I think it's pretty easy to reproduce on https://beamanalytics.io!

**Comment by mitrotasios** [comment] 2023-03-03 15:02
Awesome! And thanks for using the library for beam analytics, big fan 🤗

**Comment by mitrotasios** [comment] 2023-03-06 18:19
hey @TheBuilderJR, I have a bit of a hard time reproducing the issue. Potentially you have used the same value for the `value` key twice?

**Comment by TheBuilderJR** [comment] 2023-03-07 06:44
Hey @mitrotasios here's a video repro

https://user-images.githubusercontent.com/46176773/223343881-16b05589-d40a-487f-9367-7d78c70f15d3.mov

Here's also the two relevant files

```
import useDateFilter from "@/lib/hooks/use-date-filter";
import { DateRangePicker } from "@tremor/react";

export default function Example() {
  const {
    dateFilterOptions,
    dateRangePickerValue,
    onDateRangePickerValueChange,
  } = useDateFilter();

  return (
    <div className="min-w-[165px]">
      <DateRangePicker
        value={dateRangePickerValue}
        onValueChange={onDateRangePickerValueChange}
        options={dateFilterOptions}
        enableYearPagination
      />
    </div>
  );
}
```

```
import moment from 'moment';
import { useRouter } from "next/router";
import { useCallback, useEffect, useMemo, useState } from "react";

const dateFormat = 'YYYY-MM-DD'

const dateFilterOptions = [
    { text: 'Today', value: 'Today', startDate: new Date() },
    {
        text: 'Yesterday',
        value: 'Yesterday',
        startDate: moment().subtract(1, 'days').toDate(),
    },
    {
        text: 'Last 7 days',
        value: 'Last 7 days',
        startDate: moment().subtract(7, 'days').toDate(),
    },
    {
        text: 'Last 28 days',
        value: 'Last 28 days',
        startDate: moment().subtract(28, 'days').toDate(),
    },
    {
        text: 'Last 12 months',
        value: 'Last 12 months',
        startDate: moment().subtract(12, 'months').toDate(),
    },
]

export default function useDateFilter() {
    const router = useRouter();
    const [dateRangePickerValue, setDateRangePickerValue] =
        useState([
            moment(moment().utc()).toDate(),
            moment(moment().utc()).toDate(),
            router.query.date || "Last 7 days",
        ])


    const setDateFilter = useCallback(
        ([startDate, endDate, value]) => {
            value = value || "custom";
            let searchParams = new URLSearchParams(window.location.search);
            searchParams.set('date', value);
            if (value === "custom") {
                startDate = moment(startDate).format(dateFormat);
                endDate = moment(endDate).format(dateFormat);
                searchParams.set('date', [startDate, endDate].join(","));
            }
            router.push(
                {
                    query: searchParams.toString(),
                },
                undefined,
                { scroll: false }
            )
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        []
    );

    const lastDaysParam = (router.query.date || "Last 7 days") as string;
    const { startDate, endDate } = useMemo(() => {
        const today = moment().utc()
        if (lastDaysParam.indexOf("-") > -1) {
            const [startDate, endDate] = lastDaysParam.split(",");
            return { startDate, endDate }
        } else {
            // Unused so doesn't matter!
            const startDate = moment(today);
            const endDate = moment(today);
            return { startDate, endDate }
        }
    }, [router.query.date])

    useEffect(() => {
        const value = (router.query.date || "").indexOf(",") > -1 ? null : (router.query.date || "Last 7 days");
        setDateRangePickerValue([
            moment(startDate).toDate(),
            moment(endDate).toDate(),
            value,
        ])
    }, [startDate, endDate, router.query.date])

    const onDateRangePickerValueChange = useCallback(
        ([startDate, endDate, value]) => {
            if (startDate && endDate) {
                setDateFilter([startDate, endDate, value])
            } else {
                setDateRangePickerValue([startDate, endDate, value])
            }
        },
        [setDateFilter]
    )

    return {
        dateFilterOptions,
        dateRangePickerValue,
        // legacy
        dateFilter: {
            name: router.query.date || "Last 7 days"
        },
        onDateRangePickerValueChange,
        setDateFilter
    };
}
```

**Comment by mitrotasios** [comment] 2023-03-07 20:41
@TheBuilderJR thanks for sharing this, I could reproduce the issue indeed. It seems like the selected state somehow gets memoized so I need to debug this a bit more in the source code.

However, I think you forgot to set the `dateRangePickerValue` state in your `onDateRangePickerValueChange` function in the first part of the if statement, which seems to fix part of the issue. (You always need to set the new `dateRangePickerValue` state with every value change since its a controlled component):
```
...
const onDateRangePickerValueChange = useCallback(
      ([startDate, endDate, value]) => {
          if (startDate && endDate) {
              setDateFilter([startDate, endDate, value])
          }
          setDateRangePickerValue([startDate, endDate, value])
      },
      [setDateFilter]
 )
...
``` 
The issue then seems to persist though when loading the page for the first time, for which I would suggest the following temporary work-around: try removing the `router.query.date || "Last 7 days"` when initialising the state and set it to `undefined` or `null`. (The `useEffect` will overwrite this anyway).
```
...
const [dateRangePickerValue, setDateRangePickerValue] =
    useState([
          moment(moment().utc()).toDate(),
          moment(moment().utc()).toDate(),
          undefined,
    ])
...
```

Let me know if that works and thanks again for submitting this, I will try to push a fix in the package in the upcoming days.

**Comment by TheBuilderJR** [comment] 2023-03-07 23:20
Ah yes that fixed things. Thank you so much @mitrotasios!!

**Comment by mitrotasios** [comment] 2023-03-20 20:19
Should be resolved with the newest release.

**Closed as completed by mitrotasios** 2023-03-20 20:19 UTC
Labels: Type: Bug
