### ISSUE TITLE
Capture data on Click event

### ISSUE THREAD

**Issue by Franzcasttr** [tremorlabs/tremor-npm#381] opened 2023-03-31 06:54 UTC
Hey guys,

How to capture data on click events, If I click a chart e.g. BarChart 
I want to get the value of that chart and also highlight the charts? Something like change the opacity of the other charts?

**Comment by mitrotasios** [comment] 2023-04-02 10:22
Hey, this has been requested a lot and we'll add this behavior at some point.

**Comment by mitrotasios** [comment] 2023-04-20 15:37
duplicate of #195

**Closed as completed by mitrotasios** 2023-04-20 15:37 UTC
Labels: Type: Feature
