### ISSUE TITLE
Ability to have a trend line on top of bar charts

### ISSUE THREAD

**Issue by geordidearns** [tremorlabs/tremor-npm#101] opened 2022-10-12 12:56 UTC
SUPER nice job on the lib so far, it's been a joy to use so kudos to y'all! ⭐️

I would love to be able to show trends on top of both single and grouped bar charts. I have attached a (ugly) example, please ask if you need more context!

![Screenshot 2022-10-12 at 08 53 36](https://user-images.githubusercontent.com/5615153/195348207-6ca089d0-eb8a-416f-9890-56608204d943.png)

**Comment by mitrotasios** [comment] 2022-10-12 19:41
hi @geordidearns, thanks so much for the feedback and the general support from the very beginning! That is a useful feature indeed and we will add this to our roadmap. The feature would be quite extensive so I think we will need some time to implement this though. :)

**Comment by mitrotasios** [comment] 2023-04-20 15:47
duplicate of #377

**Closed as completed by mitrotasios** 2023-04-20 15:47 UTC
Labels: Type: Feature
