### ISSUE TITLE
new component: pure datepicker

### ISSUE THREAD

**Issue by devmanbr** [tremorlabs/tremor-npm#468] opened 2023-05-19 03:00 UTC
first I want to thank you for the excellent project!

currently, from what I've seen, it's only possible to use the datepicker in date range format, which is really useful for many cases. but it would also be useful to be able to have datepicker and datetime picker components.

in my use case, the need arose to set deadlines for solving tasks, which have date and time as deadlines.

thank you if you can implement!

**Comment by mitrotasios** [comment] 2023-05-23 15:50
Thanks for the kind words @devmanbr and for elaborating your use case. We will tackle this as soon as Tremor v3 comes out by the end of the month :) I will close this issue since it is a duplicate of #401

**Closed as completed by mitrotasios** 2023-05-23 15:50 UTC
